[config]
enable_custom_labels=true

[custom_labels."Good PR"]
description = "A good PR"
[custom_labels."Medium PR"]
description = "A medium PR"
[custom_labels."Bad PR"]
description = "A bad PR"


[pr_description]
add_original_user_description = true
keep_original_user_title = false
