[config]
enable_custom_labels=true

[custom_labels."Good PR"]
description = "A good PR"
[custom_labels."Medium PR"]
description = "A medium PR"
[custom_labels."Bad PR"]
description = "A bad PR"
[custom_labels."Code PR"]
description = "PR that contains code changes"
[custom_labels."documentation PR"]
description = "PR that contains documentation changes"

[pr_description]
add_original_user_description = true
keep_original_user_title = false
